# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-14 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0003_auto_20170913_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='edit_decimalLatitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='edit_decimalLongitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='edit_depth',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
