# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-11 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0006_auto_20170922_0945'),
        ('data_manager', '0003_auto_20170913_1717'),
    ]

    operations = [
    ]
