# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-13 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0008_auto_20171012_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persontyperole',
            options={},
        ),
        migrations.RemoveField(
            model_name='persontyperole',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='person_type_role',
            field=models.ManyToManyField(blank=True, null=True, to='data_manager.PersonTypeRole'),
        ),
    ]
