# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-26 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0010_auto_20171013_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontyperole',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personTypeRole', to='data_manager.Dataset'),
        ),
        migrations.AlterField(
            model_name='persontyperole',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personTypeRole', to='data_manager.Project'),
        ),
    ]
