# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-27 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0011_auto_20171026_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GBIFOccurrence', to='data_manager.Dataset'),
        ),
    ]
