# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-06 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0014_auto_20171106_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontyperole',
            name='organization',
            field=models.TextField(blank=True, null=True),
        ),
    ]
