# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-07 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0015_persontyperole_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='organization',
        ),
    ]
