# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-10 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0016_remove_person_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasisOfRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis_of_record', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='gbiftaxa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GBIFOccurrence', to='data_manager.GBIFTaxa'),
        ),
        migrations.AddField(
            model_name='gbifoccurrence',
            name='basis_of_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GBIFOccurrence', to='data_manager.BasisOfRecord'),
        ),
    ]
