# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-22 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0017_auto_20171110_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='record_count',
            new_name='full_record_count',
        ),
        migrations.AddField(
            model_name='dataset',
            name='filtered_record_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='percentage_records_retained',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
