# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-17 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0018_auto_20171122_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gbifoccurrence',
            options={'ordering': ('dataset_id',)},
        ),
        migrations.AlterField(
            model_name='dataset',
            name='data_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset', to='data_manager.DataType'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset', to='data_manager.Publisher'),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='basis_of_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GBIFOccurrence', to='data_manager.BasisOfRecord'),
        ),
        migrations.AlterField(
            model_name='persontyperole',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personTypeRole', to='data_manager.Dataset'),
        ),
        migrations.AlterField(
            model_name='persontyperole',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personTypeRole', to='data_manager.Person'),
        ),
        migrations.AlterField(
            model_name='persontyperole',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personTypeRole', to='data_manager.Project'),
        ),
    ]
