# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 17:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0021_download_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='download',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='download',
            name='date_created',
        ),
        migrations.AddField(
            model_name='download',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 20, 17, 23, 13, 684073), editable=False),
            preserve_default=False,
        ),
    ]
