# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0022_auto_20171220_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basisofrecord',
            options={'ordering': ('basis_of_record',)},
        ),
        migrations.AlterModelOptions(
            name='gbifoccurrence',
            options={'ordering': ('gbifID',)},
        ),
        migrations.AlterModelOptions(
            name='gbiftaxa',
            options={'ordering': ('scientificName',)},
        ),
        migrations.AlterField(
            model_name='download',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
