# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0024_auto_20180111_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gbifoccurrence',
            options={'ordering': ('pk',)},
        ),
    ]
