# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-18 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0027_dataset_deleted_record_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='gbifoccurrence',
            name='hexgrid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GBIFOccurrence', to='data_manager.HexGrid'),
        ),
    ]
