# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0030_auto_20180313_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='classKey',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='familyKey',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='genusKey',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='kingdomKey',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='orderKey',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='phylumKey',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='speciesKey',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='subgenusKey',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='taxonKey',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
