# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0031_auto_20180313_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ['-filtered_record_count']},
        ),
    ]
