# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-24 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0036_remove_statistics_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
