# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-08 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0039_dataset_download_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hexgrid',
            name='size',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
