# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-09 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0040_auto_20180508_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hexgrid',
            name='bottom',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='hexgrid',
            name='left',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='hexgrid',
            name='right',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='hexgrid',
            name='top',
            field=models.FloatField(db_index=True, null=True),
        ),
    ]
