# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-05 10:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0042_harvesteddataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvesteddataset',
            name='license',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='harvesteddataset',
            name='modified',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='harvesteddataset',
            name='publishingOrganizationTitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='harvesteddataset',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
