# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-05 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0043_auto_20180605_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvesteddataset',
            name='import_full_dataset',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='harvesteddataset',
            name='include_in_antabif',
            field=models.BooleanField(default=False),
        ),
    ]
