# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-05 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0044_auto_20180605_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvesteddataset',
            name='import_full_dataset',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='harvesteddataset',
            name='include_in_antabif',
            field=models.NullBooleanField(default=None),
        ),
    ]
