# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-07 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0042_auto_20180531_1338'),
        ('data_manager', '0045_auto_20180605_0856'),
    ]

    operations = [
    ]
