# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-10 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0046_merge_20180607_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='percentage_records_retained',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
