# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-28 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0047_auto_20180610_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='_class',
            field=models.TextField(blank=True, null=True, verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='_format',
            field=models.TextField(blank=True, null=True, verbose_name='format'),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='_type',
            field=models.TextField(blank=True, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='_class',
            field=models.TextField(blank=True, null=True, verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='_type',
            field=models.TextField(blank=True, null=True, verbose_name='type'),
        ),
    ]
