# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-06 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0049_harvesteddataset_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontyperole',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personTypeRole', to='data_manager.Dataset'),
        ),
        migrations.AlterField(
            model_name='persontyperole',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personTypeRole', to='data_manager.Person'),
        ),
        migrations.AlterField(
            model_name='persontyperole',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personTypeRole', to='data_manager.Project'),
        ),
    ]
