# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-12 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0050_auto_20180706_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
