# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-09 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0052_download_record_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvesteddataset',
            name='deleted_from_gbif',
            field=models.NullBooleanField(default=False),
        ),
    ]
