# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-16 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0054_dataset_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='gbifoccurrence',
            name='acceptedScientificName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gbifoccurrence',
            name='acceptedTaxonKey',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
