# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-19 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0056_auto_20181017_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='deleted_record_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='filtered_record_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='percentage_records_retained',
            field=models.FloatField(blank=True, default=100, null=True),
        ),
    ]
