# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-31 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0057_auto_20181019_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='intellectual_right',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='thesaurus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='given_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
