# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-28 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0059_harvesteddataset_harvested_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvesteddataset',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_manager.Dataset'),
        ),
    ]
