# Generated by Django 2.2 on 2019-05-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0060_auto_20190228_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gbifoccurrence',
            options={},
        ),
    ]
