# Generated by Django 2.2 on 2019-05-10 15:18
from django.db import migrations, connection


def make_trigger(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""CREATE TRIGGER occ_tsvector_update BEFORE INSERT OR UPDATE ON data_manager_gbifoccurrence 
        FOR EACH ROW EXECUTE FUNCTION tsvector_update_trigger(row_json, 'pg_catalog.english', row_json_text);
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0063_gbifoccurrence_row_json'),
    ]

    operations = [
        migrations.RunPython(make_trigger)
    ]
