# Generated by Django 2.2.1 on 2019-06-17 07:12

from django.db import migrations, connection


def make_trigger(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""CREATE TRIGGER eml_tsvector_update BEFORE INSERT OR UPDATE ON data_manager_dataset 
        FOR EACH ROW EXECUTE FUNCTION tsvector_update_trigger(eml_tsv, 'pg_catalog.english', eml_text);
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0066_dataset_eml_tsv'),
    ]

    operations = [
        migrations.RunPython(make_trigger)
    ]
