# Generated by Django 2.2.1 on 2019-06-18 12:20

from django.db import migrations


def delete_plazi_harvested_datasets(apps, schema_editor):
    """
    Delete all harvested dataset published by Plazi
    """
    HarvestedDataset = apps.get_model('data_manager', 'HarvestedDataset')
    queryset = HarvestedDataset.objects.filter(publishingOrganizationKey='7ce8aef0-9e92-11dc-8738-b8a03c50a862')
    for harvested_dataset in queryset:
        harvested_dataset.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0068_auto_20190617_0720'),
    ]

    operations = [
        migrations.RunPython(delete_plazi_harvested_datasets),
    ]
