# Generated by Django 2.2.1 on 2019-06-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0069_auto_20190618_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvesteddataset',
            name='deleted_from_gbif',
            field=models.NullBooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='harvesteddataset',
            name='import_full_dataset',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='harvesteddataset',
            name='include_in_antabif',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
    ]
