# Generated by Django 2.2.1 on 2019-07-01 06:38
import datetime
from django.db import migrations


def update_dataset_download_on_datetime(apps, schema_editor):
    """
    Update Dataset `download_on` field.
    Dataset `download_on` field was new, not all Dataset instances `download_on` field has a value, but it is needed to
    check for update.
    """
    Dataset = apps.get_model('data_manager', 'Dataset')
    queryset = Dataset.objects.filter(download_on__isnull=True)
    download_date = datetime.datetime(2019, 1, 1)
    queryset.update(download_on=download_date)


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0069_auto_20190618_1220'),
    ]

    operations = [
        migrations.RunPython(update_dataset_download_on_datetime),
    ]
