# Generated by Django 2.2.1 on 2019-06-24 06:36

from django.db import migrations, models


def convert_empty_string_to_none(apps, schema_editor):
    HarvestedDataset = apps.get_model('data_manager', 'HarvestedDataset')
    HarvestedDataset.objects.filter(recordCount__exact='').update(recordCount=None)


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0070_auto_20190624_0630'),
    ]

    operations = [
        migrations.RunPython(convert_empty_string_to_none),
        migrations.AlterField(
            model_name='harvesteddataset',
            name='recordCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
