# Generated by Django 2.2.1 on 2019-07-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0071_auto_20190624_0636'),
        ('data_manager', '0070_auto_20190701_0638'),
    ]

    operations = [
    ]
