# Generated by Django 2.2.1 on 2019-07-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0073_auto_20190705_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gbifoccurrence',
            old_name='edit_coordinatePrecision',
            new_name='coordinatePrecision',
        ),
        migrations.RenameField(
            model_name='gbifoccurrence',
            old_name='edit_coordinateUncertaintyInMeters',
            new_name='coordinateUncertaintyInMeters',
        ),
        migrations.RenameField(
            model_name='gbifoccurrence',
            old_name='edit_decimalLatitude',
            new_name='decimalLatitude',
        ),
        migrations.RenameField(
            model_name='gbifoccurrence',
            old_name='edit_decimalLongitude',
            new_name='decimalLongitude',
        ),
        migrations.RenameField(
            model_name='gbifoccurrence',
            old_name='edit_depth',
            new_name='depth',
        ),
        migrations.RenameField(
            model_name='gbifoccurrence',
            old_name='edit_pointRadiusSpatialFit',
            new_name='pointRadiusSpatialFit',
        ),
    ]
