# Generated by Django 2.2.1 on 2019-07-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0074_auto_20190705_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gbifoccurrence',
            old_name='day',
            new_name='raw_day',
        ),
        migrations.RenameField(
            model_name='gbifoccurrence',
            old_name='modified',
            new_name='raw_modified',
        ),
        migrations.RenameField(
            model_name='gbifoccurrence',
            old_name='month',
            new_name='raw_month',
        ),
        migrations.RenameField(
            model_name='gbifoccurrence',
            old_name='year',
            new_name='raw_year',
        ),
        migrations.RenameField(
            model_name='gbifverbatimoccurrence',
            old_name='day',
            new_name='raw_day',
        ),
        migrations.RenameField(
            model_name='gbifverbatimoccurrence',
            old_name='month',
            new_name='raw_modified',
        ),
        migrations.RenameField(
            model_name='gbifverbatimoccurrence',
            old_name='year',
            new_name='raw_month',
        ),
        migrations.AddField(
            model_name='gbifverbatimoccurrence',
            name='raw_year',
            field=models.TextField(blank=True, null=True),
        ),
    ]
