# Generated by Django 2.2.1 on 2019-07-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0075_auto_20190705_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gbifoccurrence',
            old_name='edit_day',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='gbifoccurrence',
            old_name='edit_modified',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='gbifoccurrence',
            old_name='edit_month',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='gbifoccurrence',
            old_name='edit_year',
            new_name='year',
        ),
    ]
