# Generated by Django 2.2.1 on 2019-07-12 12:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0077_auto_20190711_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvesteddataset',
            name='dataset',
            field=models.ForeignKey(blank=True, help_text='The Dataset instance associated with the HarvestedDataset instance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_manager.Dataset'),
        ),
        migrations.AlterField(
            model_name='harvesteddataset',
            name='deleted_from_gbif',
            field=models.NullBooleanField(db_index=True, default=False, help_text='Marked as deleted on GBIF'),
        ),
        migrations.AlterField(
            model_name='harvesteddataset',
            name='harvested_on',
            field=models.DateTimeField(auto_now_add=True, help_text='The date time when the HarvestedDataset instance is first created', null=True),
        ),
        migrations.AlterField(
            model_name='harvesteddataset',
            name='hostingOrganizationKey',
            field=models.CharField(blank=True, help_text='Hosting organization UUID key', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='harvesteddataset',
            name='hostingOrganizationTitle',
            field=models.CharField(blank=True, help_text='Hosting organization title', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='harvesteddataset',
            name='import_full_dataset',
            field=models.NullBooleanField(db_index=True, default=None, help_text='Flag that indicates whether the full dataset or only records within SCAR-marbin area should be imported'),
        ),
        migrations.AlterField(
            model_name='harvesteddataset',
            name='include_in_antabif',
            field=models.NullBooleanField(db_index=True, default=None, help_text='Flag to import the dataset into database'),
        ),
        migrations.AlterField(
            model_name='harvesteddataset',
            name='key',
            field=models.CharField(help_text='UUID of a dataset', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='harvesteddataset',
            name='license',
            field=models.TextField(blank=True, help_text='The type of license applied to the dataset', null=True),
        ),
        migrations.AlterField(
            model_name='harvesteddataset',
            name='modified',
            field=models.DateField(default=datetime.date.today, help_text='The last modified date time of the dataset instance'),
        ),
        migrations.AlterField(
            model_name='harvesteddataset',
            name='publishingCountry',
            field=models.CharField(blank=True, help_text='The country of the organization which own the dataset given as a ISO 639-1 (2 letter) country code', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='harvesteddataset',
            name='publishingOrganizationKey',
            field=models.CharField(blank=True, help_text='Publishing organization UUID key', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='harvesteddataset',
            name='publishingOrganizationTitle',
            field=models.CharField(blank=True, help_text='publishing organization title', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='harvesteddataset',
            name='recordCount',
            field=models.IntegerField(blank=True, help_text='The number of record associated with the dataset', null=True),
        ),
        migrations.AlterField(
            model_name='harvesteddataset',
            name='title',
            field=models.CharField(blank=True, help_text='The title of the dataset', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='harvesteddataset',
            name='type',
            field=models.CharField(blank=True, help_text='The type of dataset given in <a href="http://api.gbif.org/v1/enumeration/basic/DatasetType">DatasetType enum</a>', max_length=150, null=True),
        ),
    ]
