# Generated by Django 2.2.3 on 2019-08-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0078_auto_20190712_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='data_type',
            field=models.TextField(help_text='Row type of Core used in Darwin-Core Archive. Examples: "METADATA", "OCCURRENCE", "SAMPLING-EVENT"', unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_from_gbif',
            field=models.TextField(default='', help_text='Response data of publisher retrieved from GBIF.'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_key',
            field=models.TextField(help_text='UUID of a publisher in https://api.gbif.org/v1/organization/', unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_name',
            field=models.TextField(blank=True, help_text='Name of a publisher in https://api.gbif.org/v1/organization/'),
        ),
    ]
