# Generated by Django 2.2.3 on 2019-09-25 07:54

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0079_auto_20190823_1224'),
    ]

    operations = [
        TrigramExtension(),
        migrations.RunSQL("DROP INDEX IF EXISTS project_trgm_upper_gin_idx, keyword_trgm_upper_gin_idx, publisher_trgm_upper_gin_idx, occurrence_trgm_upper_gin_idx;"),
        migrations.RunSQL("CREATE INDEX project_trgm_upper_gin_idx ON data_manager_project USING GIN ((UPPER(title)) gin_trgm_ops);"),
        migrations.RunSQL("CREATE INDEX keyword_trgm_upper_gin_idx ON data_manager_keyword USING GIN ((UPPER(keyword)) gin_trgm_ops);"),
        migrations.RunSQL("CREATE INDEX publisher_trgm_upper_gin_idx ON data_manager_publisher USING GIN ((UPPER(publisher_name)) gin_trgm_ops);"),
        migrations.RunSQL("CREATE INDEX occurrence_trgm_upper_gin_idx ON data_manager_gbifoccurrence USING GIN ((UPPER(row_json_text)) gin_trgm_ops);")
    ]
