# Generated by Django 2.2.3 on 2019-10-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0081_auto_20190930_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
