# Generated by Django 2.2.3 on 2019-10-04 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0082_download_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/day', null=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/month', null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/year', null=True),
        ),
    ]
