# Generated by Django 2.2.3 on 2019-10-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0083_auto_20191004_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='kingdom',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/kingdom', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='phylum',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/phylum', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='_class',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/class', null=True, verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='family',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/family', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='genus',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/genus', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='kingdom',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/kingdom', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='locality',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/locality', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='occurrenceStatus',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/occurrenceStatus', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='order',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/order', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='phylum',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/phylum', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='samplingProtocol',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/samplingProtocol', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='scientificName',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/scientificName', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='scientificNameID',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/scientificNameID', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='specificEpithet',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/specificEpithet', null=True),
        ),
    ]
