# Generated by Django 2.2.3 on 2019-10-15 12:52

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0084_auto_20191004_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='abstract',
            field=models.TextField(blank=True, help_text='https://knb.ecoinformatics.org/emlparser/docs/eml-2.1.1/eml-resource.html#abstract', null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='alternate_identifiers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, help_text='https://knb.ecoinformatics.org/emlparser/docs/eml-2.1.1/eml-resource.html#alternateIdentifier', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='bounding_box',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='https://knb.ecoinformatics.org/emlparser/docs/eml-2.1.1/eml-coverage.html#geographicCoverage', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='citation',
            field=models.TextField(blank=True, help_text='https://knb.ecoinformatics.org/emlparser/docs/eml-2.1.1/eml.html#citation', null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='data_type',
            field=models.ForeignKey(blank=True, help_text='Row type of a Darwin-Core Archive. e.g.: "METADATA", "OCCURRENCE", "SAMPLING-EVENT"', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset', to='data_manager.DataType'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_key',
            field=models.TextField(help_text='https://knb.ecoinformatics.org/emlparser/docs/eml-2.1.1/eml.html#packageId', unique=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='intellectual_right',
            field=models.TextField(blank=True, help_text='https://knb.ecoinformatics.org/emlparser/docs/eml-2.1.1/eml-resource.html#intellectualRights', null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='project',
            field=models.ForeignKey(blank=True, help_text='https://knb.ecoinformatics.org/emlparser/docs/eml-2.1.1/eml-dataset.html#project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataset', to='data_manager.Project'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='pub_date',
            field=models.DateField(blank=True, help_text='https://knb.ecoinformatics.org/emlparser/docs/eml-2.1.1/eml-resource.html#pubDate', null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='publisher',
            field=models.ForeignKey(blank=True, help_text='https://knb.ecoinformatics.org/emlparser/docs/eml-2.1.1/eml-dataset.html#publisher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset', to='data_manager.Publisher'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='title',
            field=models.TextField(help_text='https://knb.ecoinformatics.org/emlparser/docs/eml-2.1.1/eml-resource.html#title'),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='_class',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/class', null=True, verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='family',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/family', null=True),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='genus',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/genus', null=True),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='kingdom',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/kingdom', null=True),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='locality',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/locality', null=True),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='occurrenceStatus',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/occurrenceStatus', null=True),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='order',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/order', null=True),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='phylum',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/phylum', null=True),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='samplingProtocol',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/samplingProtocol', null=True),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='scientificName',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/scientificName', null=True),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='scientificNameID',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/scientificNameID', null=True),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='specificEpithet',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.tdwg.org/dwc/terms/specificEpithet', null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.TextField(help_text='https://knb.ecoinformatics.org/emlparser/docs/eml-2.1.1/eml-resource.html#keyword'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='thesaurus',
            field=models.TextField(blank=True, help_text='https://knb.ecoinformatics.org/emlparser/docs/eml-2.1.1/eml-resource.html#keywordThesaurus', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.TextField(blank=True, help_text='https://knb.ecoinformatics.org/emlparser/docs/eml-2.1.1/eml-party.html#electronicMailAddress', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.TextField(help_text='Concatenation of given_name and surname.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='given_name',
            field=models.TextField(blank=True, help_text='https://knb.ecoinformatics.org/emlparser/docs/eml-2.1.1/eml-party.html#givenName', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.TextField(help_text='https://knb.ecoinformatics.org/emlparser/docs/eml-2.1.1/eml-party.html#surName'),
        ),
        migrations.AlterField(
            model_name='persontyperole',
            name='organization',
            field=models.TextField(blank=True, help_text='https://knb.ecoinformatics.org/emlparser/docs/eml-2.1.1/eml-party.html#organizationName', null=True),
        ),
        migrations.AlterField(
            model_name='persontyperole',
            name='role',
            field=models.TextField(blank=True, help_text='https://knb.ecoinformatics.org/emlparser/docs/eml-2.1.1/eml-party.html#RoleType', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding',
            field=models.TextField(blank=True, help_text='https://knb.ecoinformatics.org/emlparser/docs/eml-2.1.1/eml-project.html#funding', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(help_text='https://knb.ecoinformatics.org/emlparser/docs/eml-2.1.1/eml-project.html#title'),
        ),
    ]
