# Generated by Django 2.2.3 on 2019-10-16 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0004_auto_20190516_0412'),
        ('data_manager', '0086_custom_index_for_dataset_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadResult',
            fields=[
                ('taskresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_results.TaskResult')),
            ],
            bases=('django_celery_results.taskresult',),
        ),
        migrations.RemoveField(
            model_name='download',
            name='status',
        ),
        migrations.AddField(
            model_name='download',
            name='task_results',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Download', to='data_manager.DownloadResult'),
        ),
    ]
