# Generated by Django 2.2.3 on 2019-10-16 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0087_auto_20191016_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='task_results',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Download', to='django_celery_results.TaskResult'),
        ),
        migrations.DeleteModel(
            name='DownloadResult',
        ),
    ]
