# Generated by Django 2.2.3 on 2019-12-03 13:41

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0088_auto_20191016_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='abstract',
            field=models.TextField(blank=True, help_text='https://eml.ecoinformatics.org/schema/eml-resource_xsd.html#ResourceGroup_abstract', null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='alternate_identifiers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, help_text='https://eml.ecoinformatics.org/schema/eml-resource_xsd.html#ResourceGroup_alternateIdentifier', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='bounding_box',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='https://eml.ecoinformatics.org/schema/eml-coverage_xsd.html#Coverage_geographicCoverage', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='citation',
            field=models.TextField(blank=True, help_text='https://eml.ecoinformatics.org/schema/eml_xsd.html#eml_citation', null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_key',
            field=models.TextField(help_text='https://eml.ecoinformatics.org/schema/eml_xsd.html#eml_packageId', unique=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='intellectual_right',
            field=models.TextField(blank=True, help_text='https://eml.ecoinformatics.org/schema/eml-resource_xsd.html#ResourceGroup_intellectualRights', null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='project',
            field=models.ForeignKey(blank=True, help_text='https://eml.ecoinformatics.org/schema/eml-project_xsd.html', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataset', to='data_manager.Project'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='pub_date',
            field=models.DateField(blank=True, help_text='https://eml.ecoinformatics.org/schema/eml-resource_xsd.html#ResourceGroup_pubDate', null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='publisher',
            field=models.ForeignKey(blank=True, help_text='https://eml.ecoinformatics.org/schema/eml-dataset_xsd.html#DatasetType_publisher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset', to='data_manager.Publisher'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='title',
            field=models.TextField(help_text='https://eml.ecoinformatics.org/schema/eml-resource_xsd.html#ResourceGroup_title'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.TextField(help_text='https://eml.ecoinformatics.org/schema/eml-resource_xsd.html#ResourceGroup_ResourceGroup_keywordSet_keyword'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='thesaurus',
            field=models.TextField(blank=True, help_text='https://eml.ecoinformatics.org/schema/eml-resource_xsd.html#ResourceGroup_ResourceGroup_keywordSet_keywordThesaurus', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.TextField(blank=True, help_text='https://eml.ecoinformatics.org/schema/eml-party_xsd.html#ResponsibleParty_electronicMailAddress', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='given_name',
            field=models.TextField(blank=True, help_text='https://eml.ecoinformatics.org/schema/eml-party_xsd.html#Person_givenName', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.TextField(help_text='https://eml.ecoinformatics.org/schema/eml-party_xsd.html#Person_surName'),
        ),
        migrations.AlterField(
            model_name='persontyperole',
            name='organization',
            field=models.TextField(blank=True, help_text='https://eml.ecoinformatics.org/schema/eml-party_xsd.html#ResponsibleParty_organizationName', null=True),
        ),
        migrations.AlterField(
            model_name='persontyperole',
            name='role',
            field=models.TextField(blank=True, help_text='https://eml.ecoinformatics.org/schema/eml-party_xsd.html#RoleType', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding',
            field=models.TextField(blank=True, help_text='https://eml.ecoinformatics.org/eml-project.html#funding', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(help_text='https://eml.ecoinformatics.org/eml-project.html#title'),
        ),
    ]
