# Generated by Django 2.2.3 on 2020-01-08 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0090_remove_download_task_results'),
    ]

    operations = [
        migrations.RenameField(
            model_name='download',
            old_name='name',
            new_name='task_id',
        ),
    ]
