# Generated by Django 2.2.3 on 2020-02-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0092_update_download_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='_class',
            field=models.TextField(blank=True, help_text='http://rs.tdwg.org/dwc/terms/class', null=True, verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='acceptedTaxonKey',
            field=models.TextField(blank=True, help_text='http://rs.gbif.org/terms/1.0/acceptedTaxonKey', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='classKey',
            field=models.TextField(blank=True, help_text='http://rs.gbif.org/terms/1.0/classKey', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='family',
            field=models.TextField(blank=True, help_text='http://rs.tdwg.org/dwc/terms/family', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='familyKey',
            field=models.TextField(blank=True, help_text='http://rs.gbif.org/terms/1.0/familyKey', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='genus',
            field=models.TextField(blank=True, help_text='http://rs.tdwg.org/dwc/terms/genus', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='genusKey',
            field=models.TextField(blank=True, help_text='http://rs.gbif.org/terms/1.0/genusKey', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='kingdom',
            field=models.TextField(blank=True, help_text='http://rs.tdwg.org/dwc/terms/kingdom', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='kingdomKey',
            field=models.TextField(blank=True, help_text='http://rs.gbif.org/terms/1.0/kingdomKey', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='order',
            field=models.TextField(blank=True, help_text='http://rs.tdwg.org/dwc/terms/order', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='orderKey',
            field=models.TextField(blank=True, help_text='http://rs.gbif.org/terms/1.0/orderKey', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='phylum',
            field=models.TextField(blank=True, help_text='http://rs.tdwg.org/dwc/terms/phylum', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='phylumKey',
            field=models.TextField(blank=True, help_text='http://rs.gbif.org/terms/1.0/phylumKey', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='speciesKey',
            field=models.TextField(blank=True, help_text='http://rs.gbif.org/terms/1.0/speciesKey', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='specificEpithet',
            field=models.TextField(blank=True, help_text='http://rs.tdwg.org/dwc/terms/specificEpithet', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='subgenusKey',
            field=models.TextField(blank=True, help_text='http://rs.gbif.org/terms/1.0/subgenusKey', null=True),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='_class',
            field=models.TextField(blank=True, help_text='http://rs.tdwg.org/dwc/terms/class', null=True, verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='family',
            field=models.TextField(blank=True, help_text='http://rs.tdwg.org/dwc/terms/family', null=True),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='genus',
            field=models.TextField(blank=True, help_text='http://rs.tdwg.org/dwc/terms/genus', null=True),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='kingdom',
            field=models.TextField(blank=True, help_text='http://rs.tdwg.org/dwc/terms/kingdom', null=True),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='order',
            field=models.TextField(blank=True, help_text='http://rs.tdwg.org/dwc/terms/order', null=True),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='phylum',
            field=models.TextField(blank=True, help_text='http://rs.tdwg.org/dwc/terms/phylum', null=True),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='specificEpithet',
            field=models.TextField(blank=True, help_text='http://rs.tdwg.org/dwc/terms/specificEpithet', null=True),
        ),
    ]
