# Generated by Django 2.2.3 on 2020-02-04 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0094_remove_dataset_eml_tsv'),
    ]

    operations = [
        migrations.RunSQL("DROP INDEX IF EXISTS dataset_idx;"),
        migrations.RunSQL("DROP TRIGGER IF EXISTS eml_tsvector_update ON data_manager_dataset;")
    ]
