# Generated by Django 2.2.3 on 2020-02-04 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0097_auto_20200204_0842'),
    ]

    operations = [
        # iexact search
        migrations.RunSQL("CREATE INDEX upper_occurrence_status_idx on data_manager_gbifoccurrence ((UPPER('occurrenceStatus')));"),
        # icontains search
        migrations.RunSQL("CREATE INDEX upper_sampling_protocol_idx on data_manager_gbifoccurrence USING GIN (UPPER('samplingProtocol') gin_trgm_ops);"),
        migrations.RunSQL("CREATE INDEX upper_locality_idx on data_manager_gbifoccurrence USING GIN (UPPER('locality') gin_trgm_ops);"),
        migrations.RunSQL("CREATE INDEX upper_scientific_name_idx on data_manager_gbifoccurrence USING GIN (UPPER('scientificName') gin_trgm_ops);"),
    ]

