# Generated by Django 2.2.3 on 2020-02-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0098_auto_20200204_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='locality',
            field=models.TextField(blank=True, help_text='http://rs.tdwg.org/dwc/terms/locality', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='occurrenceStatus',
            field=models.TextField(blank=True, help_text='http://rs.tdwg.org/dwc/terms/occurrenceStatus', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='samplingProtocol',
            field=models.TextField(blank=True, help_text='http://rs.tdwg.org/dwc/terms/samplingProtocol', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='scientificName',
            field=models.TextField(blank=True, help_text='http://rs.tdwg.org/dwc/terms/scientificName', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='scientificNameID',
            field=models.TextField(blank=True, help_text='http://rs.tdwg.org/dwc/terms/scientificNameID', null=True),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='locality',
            field=models.TextField(blank=True, help_text='http://rs.tdwg.org/dwc/terms/locality', null=True),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='occurrenceStatus',
            field=models.TextField(blank=True, help_text='http://rs.tdwg.org/dwc/terms/occurrenceStatus', null=True),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='samplingProtocol',
            field=models.TextField(blank=True, help_text='http://rs.tdwg.org/dwc/terms/samplingProtocol', null=True),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='scientificName',
            field=models.TextField(blank=True, help_text='http://rs.tdwg.org/dwc/terms/scientificName', null=True),
        ),
        migrations.AlterField(
            model_name='gbifverbatimoccurrence',
            name='scientificNameID',
            field=models.TextField(blank=True, help_text='http://rs.tdwg.org/dwc/terms/scientificNameID', null=True),
        ),
    ]
