# Generated by Django 2.2.3 on 2020-03-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0099_auto_20200204_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
