# Generated by Django 2.2.3 on 2020-06-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0101_auto_20200516_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gbifoccurrence',
            name='verbatimElevation',
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='classKey',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.gbif.org/terms/1.0/classKey', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='familyKey',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.gbif.org/terms/1.0/familyKey', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='genusKey',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.gbif.org/terms/1.0/genusKey', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='kingdomKey',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.gbif.org/terms/1.0/kingdomKey', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='orderKey',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.gbif.org/terms/1.0/orderKey', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='phylumKey',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.gbif.org/terms/1.0/phylumKey', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='speciesKey',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.gbif.org/terms/1.0/speciesKey', null=True),
        ),
        migrations.AlterField(
            model_name='gbifoccurrence',
            name='subgenusKey',
            field=models.TextField(blank=True, db_index=True, help_text='http://rs.gbif.org/terms/1.0/subgenusKey', null=True),
        ),
    ]
