# Generated by Django 2.2.13 on 2020-07-10 10:22

from django.db import migrations


def delete_unwanted_harvested_dataset(apps, schema_editor):
    """
    Changes in results returned from GBIF API resulting in a lot of dataset search results harvested that are not
    related to the query. This function delete those entries which actions were not taken.
    """
    HarvestedDataset = apps.get_model('data_manager', 'HarvestedDataset')
    qs = HarvestedDataset.objects.filter(include_in_antabif=None, import_full_dataset=None, dataset__isnull=True)
    while qs.exists():
        HarvestedDataset.objects.filter(pk__in=qs.values_list('pk')[:100]).delete()
    return


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0103_auto_20200612_0412'),
    ]

    operations = [
        migrations.RunPython(delete_unwanted_harvested_dataset),
    ]
